server:
  port: 8010

logging:
  level:
    root: INFO
    com.xiao: DEBUG
spring:
  application:
    name: microservice-createoOrder
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}