server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  application:
    name: ui-web
logging:
  level:
    root: INFO
    com.xiao: DEBUG
app:
  session:
    redisServer: 192.168.8.101
    redisPort: 6379
    connectTimeOut: 2000
#数据源
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    orderDBMaster:
        url: jdbc:mysql://localhost:3306/master?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        initial-size: 5
        min-idle: 1
        max-active: 5
        test-on-borrow: true
    orderDBSlave:
        url: jdbc:mysql://localhost:3306/slave?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        initial-size: 5
        min-idle: 1
        max-active: 5
        test-on-borrow: true
mybatis:
  mapper-locations: classpath:/mybatis/**/**/*Mapper.xml
  type-aliases-package: com.ekong.entity
